steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'spring-boot-graphql'
      - '--region=us-central1'
      - '--allow-unauthenticated'
      - '--image'
      - 'us-central1-docker.pkg.dev/eighth-saga-474816-a6/dataflow-docker-artifactory/spring-boot-graphql:${_IMAGE_VERSION}'
      # Networking - Mandatory combo for Direct VPC Egress
      - '--network=default'
      - '--subnet=default'
      - '--vpc-egress=private-ranges-only'
      # Security - Using the specific secret flag is safer than env-vars
      - '--set-secrets=SPRING_REDIS_PASSWORD=spring-redis-password:1'
      - '--set-env-vars'
      - '--add-cloudsql-instances=eighth-saga-474816-a6:us-central1:spring-security'
      - 'SPRING_PROFILES_ACTIVE=$_PROFILE,SPRING_CLOUD_GCP_SQL_DATABASE_NAME=library,SPRING_CLOUD_GCP_SQL_INSTANCE_CONNECTION_NAME=eighth-saga-474816-a6:us-central1:spring-security'
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_VERSION: latest
  _PROFILE: dev