resilience4j:
  circuitbreaker:
    instances:
      authorService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        ignoreExceptions:
          - com.example.exception.ValidationException
          - com.example.exception.BusinessRuleException
  retry:
    instances:
      authorService:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        randomizedWaitFactor: 0.5 # Jitter
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
  ratelimiter:
    instances:
      authorService:
        limitForPeriod: 1 #The number of permissions available in one cycle (e.g., 1 requests).
        limitRefreshPeriod: 1s #How often the permissions reset (e.g., 1s means 1 requests per second).
        timeoutDuration: 0 #How long a thread should "park" and wait for a permit if the limit is reached. Set to 0 to fail immediately.
        registerHealthIndicator: true

#resilience4j:
#  circuitbreaker:
#    configs:
#      # A global default that applies to all instances unless overridden
#      default:
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 10s
#
#      # A specialized config for external APIs
#      externalApiConfig:
#        slidingWindowSize: 5
#        failureRateThreshold: 20
#        waitDurationInOpenState: 5s
#
#    instances:
#      # This instance uses the "default" config automatically
#      authorService:
#        baseConfig: default
#
#      # This instance uses the stricter "externalApiConfig"
#      paymentService:
#        baseConfig: externalApiConfig
#
#      # This instance uses "default" but overrides one specific value
#      userService:
#        baseConfig: default
#        failureRateThreshold: 80